services:
  anirra:
    container_name: anirra
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /start.sh
    env_file: .env
    environment:
      - APP_LEVEL=DEV
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/eslint.config.mjs:/app/eslint.config.mjs
      - ./frontend/components.json:/app/components.json
      - ./src:/project/src
      - ./data:/project/data
      - ./config.yaml:/project/config.yaml
    ports:
      - 3000:3000
      - 8000:8000
