services:
  anirra:
    container_name: anirra
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /start.sh
    environment:
      - APP_LEVEL=PROD
    volumes:
      - ./data:/project/data
      - ./config.yaml:/project/config.yaml
    ports:
      - 3000:3000
      - 8000:8000
